import{a as L,S,i as a}from"./assets/vendor-73qhTu8_.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const q="55686404-067947f5ffb7fa0cb4c06d340",w="https://pixabay.com/api/";async function g(e,r=1){const o={key:q,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15};return(await L.get(w,{params:o})).data}const f=document.querySelector(".gallery"),$=document.querySelector(".loader"),v=document.querySelector(".btn-load");let M=new S(".gallery a",{captionsData:"alt",captionDelay:250});function m(e,r=!1){const o=e.map(({webformatURL:n,largeImageURL:t,tags:s,likes:i,views:y,comments:h,downloads:b})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${t}">
        <img class="gallery-image" src="${n}" alt="${s}" width="360"/>
      </a>
      <div class="info">
        <p class="info-item"><b>Likes:</b> <span>${i}</span></p>
        <p class="info-item"><b>Views:</b> <span>${y}</span></p>
        <p class="info-item"><b>Comments:</b> <span>${h}</span></p>
        <p class="info-item"><b>Downloads:</b> <span>${b}</span></p>
      </div>
    </li>`).join("");r?f.insertAdjacentHTML("beforeend",o):f.innerHTML=o,M.refresh()}function P(){f.innerHTML=""}function l(e){$.classList.toggle("is-hidden",!e)}function u(e){v.classList.toggle("is-hidden",!e)}const B=document.querySelector(".form"),E=document.querySelector(".btn-load");let c=1,d="";const p=15;B.addEventListener("submit",H);E.addEventListener("click",O);async function H(e){e.preventDefault();const r=e.currentTarget.elements["search-text"].value.trim();if(r===""){a.warning({message:"Please enter a search query!"});return}d=r,c=1,P(),u(!1),l(!0);try{const o=await g(d,c);if(o.hits.length===0){a.error({message:"Sorry, no images matching your query. Try again!"});return}m(o.hits,!1),o.totalHits<=p?a.info({message:"We're sorry, but you've reached the end of search results."}):u(!0),e.target.reset()}catch(o){a.error({message:`Error: ${o.message}`})}finally{l(!1)}}async function O(){c+=1,u(!1),l(!0);try{const e=await g(d,c);m(e.hits,!0);const r=Math.ceil(e.totalHits/p);c>=r?a.info({message:"We're sorry, but you've reached the end of search results."}):u(!0),T()}catch(e){a.error({message:`Error: ${e.message}`})}finally{l(!1)}}function T(){const e=document.querySelector(".gallery-item");if(e){const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
