import{a as q,S as v,i as n}from"./assets/vendor-73qhTu8_.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const P="55686404-067947f5ffb7fa0cb4c06d340",$="https://pixabay.com/api/";async function f(r,s=1){const t={key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15};return(await q.get($,{params:t})).data}const m=document.querySelector(".gallery"),h=document.querySelector(".loader");document.querySelector(".load-more");let M=new v(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const s=r.map(({webformatURL:t,largeImageURL:a,tags:e,likes:o,views:i,comments:w,downloads:S})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${a}">
        <img class="gallery-image" src="${t}" alt="${e}" width="360"/>
      </a>
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${o}</p>
        <p class="info-item"><b>Views:</b> ${i}</p>
        <p class="info-item"><b>Comments:</b> ${w}</p>
        <p class="info-item"><b>Downloads:</b> ${S}</p>
      </div>
    </li>`).join("");m.insertAdjacentHTML("beforeend",s),M.refresh()}function B(){m.innerHTML=""}function g(){h.classList.remove("is-hidden")}function p(){h.classList.add("is-hidden")}const E=document.querySelector(".form"),u=document.querySelector(".btn-load");let c=1,l="";const b=15,L=()=>u.classList.remove("is-hidden"),d=()=>u.classList.add("is-hidden");E.addEventListener("submit",O);u.addEventListener("click",x);async function O(r){r.preventDefault();const s=r.currentTarget.elements["search-text"].value.trim();if(s===""){n.error({message:"Please enter a search query!"});return}l=s,c=1,B(),d(),g();try{const t=await f(l,c);if(t.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}y(t.hits),t.totalHits>b&&L()}catch(t){n.error({message:`Error: ${t.message}`})}finally{p(),r.target.reset()}}async function x(){c+=1,d(),g();try{const r=await f(l,c);y(r.hits);const s=Math.ceil(r.totalHits/b);c>=s?(d(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"})):L();const t=document.querySelectorAll(".gallery-item");if(t.length>0){const a=t[0].getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}}catch(r){n.error({message:`Error: ${r.message}`})}finally{p()}}
//# sourceMappingURL=index.js.map
